//
// Created by alessandro-conti on 02/04/25.
//

#ifndef BINARY_SEARCH_MONOBOUND_INTERPOLATED_BINARY_SEARCH_H
#define BINARY_SEARCH_MONOBOUND_INTERPOLATED_BINARY_SEARCH_H


class monobound_interpolated_binary_search {

};


#endif //BINARY_SEARCH_MONOBOUND_INTERPOLATED_BINARY_SEARCH_H
